### ISSUE TITLE
运行时出现错误

### ISSUE THREAD

**Issue by SimonY2** [reskayoi/starvalley-png-to-fs#1]
我在根目录新建了一个config.ini，并且把图片放在了根目录，但是发生了这个错误，我该怎么解决：
loading pack hats...
Traceback (most recent call last):
  File "D:\星露谷\new\starvalley-png-to-fs-or-ja-master\spriteslider.py", line 98, in <module>
    main()
  File "D:\星露谷\new\starvalley-png-to-fs-or-ja-master\spriteslider.py", line 87, in main
    slider(PicConf(config[pack_config],pack_mode), work_dir)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\星露谷\new\starvalley-png-to-fs-or-ja-master\Sprite\PicConf.py", line 17, in __init__
    self.pic_type = Template.get_type(pack_mode,str(config["type"]))
                                                    ~~~~~~^^^^^^^^
  File "D:\Yingyong\anaconda\Lib\configparser.py", line 1273, in __getitem__
    raise KeyError(key)
KeyError: 'type'

**Comment by reskayoi** [comment]
可以提供您的config.ini么，似乎是没有读取到名字是type的配置项导致的

**Comment by reskayoi** [comment]
您好，FS模式提供的配置文件样例有误，请用新的配置文件格式重新试下
