### ISSUE TITLE
我在更改shirts时出现了错误

### ISSUE THREAD

**Issue by buaichixiangc** [reskayoi/starvalley-png-to-fs#2]
config文件一切正常，但最后却出现了错误
run in FS mode
work dir:[FS]Jellyfish
loaded ./Template/FSTemplate/manifest.json
save mod manifest to [FS]Jellyfish/manifest.json success

loading pack shirts...
Traceback (most recent call last):
  File "spriteslider.py", line 98, in <module>
    main()
  File "spriteslider.py", line 87, in main
    slider(PicConf(config[pack_config],pack_mode), work_dir)
  File "C:\starvalley-png-to-fs-or-ja-master\Sprite\PicConf.py", line 37, in __init__
    self.slide_width, self.slide_height, self.need_resize)
  File "C:\starvalley-png-to-fs-or-ja-master\Tool\FileTool.py", line 43, in load_no_blank_img
    return remove_img_blank(img, sprite_width, sprite_hight, need_resize)
  File "C:\starvalley-png-to-fs-or-ja-master\Tool\FileTool.py", line 92, in remove_img_blank
    if not is_blank(slide_img):
  File "C:\starvalley-png-to-fs-or-ja-master\Tool\FileTool.py", line 52, in is_blank
    if pixel[3] != 0:
IndexError: tuple index out of range
元组索引超出范围
但config一切正常，并且转hats时也能成功

**Comment by reskayoi** [comment]
您好回复有些晚了致歉，方便提供下配置和原始图片文件用于排查么

**Comment by buaichixiangc** [comment]
我已经解决了！非常好用的工具！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2025年2月20日(周四) 晚上6:29
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [reskayoi/starvalley-png-to-fs-or-ja] 我在更改shirts时出现了错误 (Issue #2)


   
您好回复有些晚了致歉，方便提供下配置和原始图片文件用于排查么

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;
  reskayoi left a comment (reskayoi/starvalley-png-to-fs-or-ja#2)
 
您好回复有些晚了致歉，方便提供下配置和原始图片文件用于排查么
